12:19:35.437 com.ibm.rmi.corba.ClientDelegate invoke:717 P=363199:O=0:CT ORBRas[default]  org.omg.CORBA.UNKNOWN: 
	>> SERVER (id=4773e3aa, host=HP-ENVY-15-x360-PC) TRACE START:
	>>    javax.ejb.EJBTransactionRolledbackException: nested exception is: javax.transaction.RollbackException
	>>	 at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapCSIException(BusinessExceptionMappingStrategy.java:167)
	>>	 at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapCSITransactionRolledBackException(BusinessExceptionMappingStrategy.java:618)
	>>	 at com.ibm.ejs.container.EJSDeployedSupport.mapCSITransactionRolledBackException(EJSDeployedSupport.java:700)
	>>	 at com.ibm.ejs.container.EJSContainer.postInvokeRolledbackException(EJSContainer.java:4886)
	>>	 at com.ibm.ejs.container.EJSContainer.postInvoke(EJSContainer.java:4572)
	>>	 at com.souschef.domain.client.EJSRemote0SLRecypeManagerRemoteBean_4270af0e.saveRecype(EJSRemote0SLRecypeManagerRemoteBean_4270af0e.java)
	>>	 at com.souschef.domain.client._EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.saveRecype(_EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.java:1)
	>>	 at com.souschef.domain.client._EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie._invoke(_EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.java)
	>>	 at com.ibm.CORBA.iiop.ServerDelegate.dispatchInvokeHandler(ServerDelegate.java:638)
	>>	 at com.ibm.CORBA.iiop.ServerDelegate.dispatch(ServerDelegate.java:508)
	>>	 at com.ibm.rmi.iiop.ORB.process(ORB.java:613)
	>>	 at com.ibm.CORBA.iiop.ORB.process(ORB.java:1584)
	>>	 at com.ibm.rmi.iiop.Connection.doRequestWork(Connection.java:3190)
	>>	 at com.ibm.rmi.iiop.Connection.doWork(Connection.java:3051)
	>>	 at com.ibm.rmi.iiop.WorkUnitImpl.doWork(WorkUnitImpl.java:64)
	>>	 at com.ibm.ejs.oa.pool.PooledThread.run(ThreadPool.java:118)
	>>	 at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
	>> SERVER (id=4773e3aa, host=HP-ENVY-15-x360-PC) TRACE END.
  vmcid: IBM  minor code: E86 completed: Maybe
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at com.ibm.rmi.iiop.ReplyMessage._getSystemException(ReplyMessage.java:345)
	at com.ibm.rmi.iiop.ReplyMessage.getSystemException(ReplyMessage.java:215)
	at com.ibm.rmi.iiop.ClientResponseImpl.getSystemException(ClientResponseImpl.java:239)
	at com.ibm.rmi.corba.ClientDelegate.intercept(ClientDelegate.java:868)
	at com.ibm.rmi.corba.ClientDelegate.invoke(ClientDelegate.java:438)
	at com.ibm.CORBA.iiop.ClientDelegate.invoke(ClientDelegate.java:1355)
	at com.ibm.rmi.corba.ClientDelegate.invoke(ClientDelegate.java:694)
	at com.ibm.CORBA.iiop.ClientDelegate.invoke(ClientDelegate.java:1385)
	at org.omg.CORBA.portable.ObjectImpl._invoke(ObjectImpl.java:484)
	at com.souschef.domain.client._RecypeManagerRemote_Stub.saveRecype(_RecypeManagerRemote_Stub.java:1)
	at com.souschef.domain.model.RecypeManagerTest.testAddRecypes(RecypeManagerTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

12:19:35.569 com.ibm.rmi.corba.ClientDelegate invoke:753 P=363199:O=0:CT ORBRas[default]  javax.ejb.EJBTransactionRolledbackException: nested exception is: javax.transaction.RollbackException
	at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapCSIException(BusinessExceptionMappingStrategy.java:167)
	at com.ibm.ejs.container.BusinessExceptionMappingStrategy.mapCSITransactionRolledBackException(BusinessExceptionMappingStrategy.java:618)
	at com.ibm.ejs.container.EJSDeployedSupport.mapCSITransactionRolledBackException(EJSDeployedSupport.java:700)
	at com.ibm.ejs.container.EJSContainer.postInvokeRolledbackException(EJSContainer.java:4886)
	at com.ibm.ejs.container.EJSContainer.postInvoke(EJSContainer.java:4572)
	at com.souschef.domain.client.EJSRemote0SLRecypeManagerRemoteBean_4270af0e.saveRecype(EJSRemote0SLRecypeManagerRemoteBean_4270af0e.java)
	at com.souschef.domain.client._EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.saveRecype(_EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.java:1)
	at com.souschef.domain.client._EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie._invoke(_EJSRemote0SLRecypeManagerRemoteBean_4270af0e_Tie.java)
	at com.ibm.CORBA.iiop.ServerDelegate.dispatchInvokeHandler(ServerDelegate.java:638)
	at com.ibm.CORBA.iiop.ServerDelegate.dispatch(ServerDelegate.java:508)
	at com.ibm.rmi.iiop.ORB.process(ORB.java:613)
	at com.ibm.CORBA.iiop.ORB.process(ORB.java:1584)
	at com.ibm.rmi.iiop.Connection.doRequestWork(Connection.java:3190)
	at com.ibm.rmi.iiop.Connection.doWork(Connection.java:3051)
	at com.ibm.rmi.iiop.WorkUnitImpl.doWork(WorkUnitImpl.java:64)
	at com.ibm.ejs.oa.pool.PooledThread.run(ThreadPool.java:118)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
Caused by: javax.transaction.RollbackException
	at com.ibm.tx.jta.impl.TransactionImpl.stage3CommitProcessing(TransactionImpl.java:1272)
	at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:1042)
	at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:963)
	at com.ibm.ws.tx.jta.TranManagerImpl.commit(TranManagerImpl.java:439)
	at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:191)
	at com.ibm.ejs.csi.TranStrategy.commit(TranStrategy.java:949)
	at com.ibm.ejs.csi.TranStrategy.postInvoke(TranStrategy.java:262)
	at com.ibm.ejs.csi.TransactionControlImpl.postInvoke(TransactionControlImpl.java:567)
	at com.ibm.ejs.container.EJSContainer.postInvoke(EJSContainer.java:4486)
	... 12 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1434)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3190)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2404)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:467)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:320)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at com.souschef.hibernate.WebSphereExtendedJtaPlatform$TransactionManagerAdapter$TransactionAdapter$1.invoke(WebSphereExtendedJtaPlatform.java:178)
	at com.sun.proxy.$Proxy50.beforeCompletion(Unknown Source)
	at com.ibm.ws.jtaextensions.SynchronizationCallbackWrapper.beforeCompletion(SynchronizationCallbackWrapper.java:66)
	at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeBefore(RegisteredSyncs.java:291)
	at com.ibm.ws.tx.jta.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:153)
	at com.ibm.ws.tx.jta.TransactionImpl.prePrepare(TransactionImpl.java:2384)
	at com.ibm.ws.tx.jta.TransactionImpl.stage1CommitProcessing(TransactionImpl.java:588)
	at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:1029)
	... 19 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3001)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3501)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:89)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:586)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:460)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1428)
	... 34 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("C##SOUSCHEF"."INGREDIENT"."RECYPE_ID")

	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:996)
	at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:892)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForDescribe(T2CPreparedStatement.java:686)
	at oracle.jdbc.driver.T2CPreparedStatement.executeForRows(T2CPreparedStatement.java:942)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4875)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.pmiExecuteUpdate(WSJdbcPreparedStatement.java:1261)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate(WSJdbcPreparedStatement.java:808)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	... 43 more

